---
name: docker
on:
  push: 
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  docker:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: docker build . -t home
      - run: docker run --rm home echo Hello
